name: Upload To Chrome Web Store
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - v**
jobs:
  build:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./build/video_speed_controller.zip ./src -i * -x *.git*

      - name: Upload to
        uses: trmcnvn/chrome-addon@v1
        with:
          extension: "nffaoalbilbmmfgbnbgppjihopabppdk"
          zip: build/video_speed_controller.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
